apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ if $val }}{{ $val | b64enc }}{{ else }}""{{ end }}{{ end }}